#!/usr/bin/env python3

import argparse
import subprocess
import os

parser = argparse.ArgumentParser()
default_image = os.environ.get('DEFAULT_DOCKER_IMAGE', 'nvcr.io/nvidia/merlin/merlin-pytorch-training:22.05')
parser.add_argument('-i', '--image', help='name of the docker image to run', type=str, default=default_image)
parser.add_argument('-c', '--cmd', help='cmd to run', type=str, default='jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=""')
parser.add_argument('-np', '--no-port-forwarding', help='forward port 8888', action='store_true')

args = parser.parse_args()

docker_cmd = ['docker run -it --rm --gpus all --ipc=host']
if args.no_port_forwarding is False:
    docker_cmd.append('-p 8888:8888')
docker_cmd.append('--mount src=`pwd`,target=/workspace,type=bind --ulimit memlock=-1 --ulimit stack=67108864 --entrypoint="" -w /workspace')
docker_cmd += [args.image, args.cmd]

subprocess.call(' '.join(docker_cmd), shell=True)
